export const BodyIsiKrs = [
    {
        No: 1,
        Ambil: <input type="checkbox" name="ambil" />,
        Kode: "INF104",
        MataKuliah: "Struktur Data dan Algoritma",
        SKS: 3,
        Kelas: "A",
        Pengajar: "Alim Misbullah, S.Si., M.S.",
        Ruang: "E.03.01",
        Tanggal: "Senin, 12 April 2021 [08:00]",
        Nilai: "A",
        NilaiDesimal: "4.0",
        Semester: "4",
        NilaiHuruf: "Nilai Huruf",
        BobotSKS: "Bobot SKS",
        SemesterIni: "Semester Ini",
        SemesterKumulatif: "Semester Kumulatif",
        MaksSksYAD: "Maksimum SKS YAD",
        KreditBeban: "Kredit Beban",
        KreditDicapai: "Kredit Dicapai",
        Ip: "IP",
    },
    {
        No: 2,
        Ambil: <input type="checkbox" name="ambil" />,
        Kode: "INF104",
        MataKuliah: "Struktur Data dan Algoritma",
        SKS: 3,
        Kelas: "A",
        Pengajar: "Alim Misbullah, S.Si., M.S.",
        Ruang: "E.03.01",
        Tanggal: "Senin, 12 April 2021 [08:00]",
        Nilai: "AB",
        NilaiDesimal: "3.5",
        Semester: "4",
        NilaiHuruf: "Nilai Huruf",
        BobotSKS: "Bobot SKS",
        SemesterIni: "Semester Ini",
        SemesterKumulatif: "Semester Kumulatif",
        MaksSksYAD: "Maksimum SKS YAD",
        KreditBeban: "Kredit Beban",
        KreditDicapai: "Kredit Dicapai",
        Ip: "IP",
    },
];

export default {
    BodyIsiKrs,
};
